version: '3.8'
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata: